
[env]
TERM = "xterm-256color"

# Tmux start
[terminal.shell]
program = "/bin/zsh"
# args = ["-l", "-c", "tmux"]


[window]
dynamic_padding = false
opacity = 0.9


[window.dimensions]
columns = 200
lines = 40

[window.padding]
x = 10
y = 10

[font]
size = 14

[selection]
save_to_clipboard = true

[general]
live_config_reload = true

# Catppuccin theme
import = ["~/.config/alacritty/catppuccin/catppuccin.toml"]

# Dracula Theme
#import = ["~/.config/alacritty/dracula/dracula.toml"]

[terminal]

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Medium"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"
